import * as fs from 'fs/promises';
import * as path from 'path';
import { VaultService } from './vault.service';
import { SpecGeneratorService } from './spec-generator.service';

/**
 * SpecKitService - Scaffolds project directories for Claude Code development.
 *
 * Creates project structure with:
 * - .claude/CLAUDE.md — Claude Code instructions
 * - .beads/ — Per-project coding memory
 * - specs/ — Generated technical specifications
 * - src/ — Source code directory
 */

const PROJECTS_DIR = '/srv/focus-flow/02_projects/active';

export class SpecKitService {
  private vault = new VaultService();
  private specGenerator = new SpecGeneratorService();

  /**
   * Scaffold a new project directory from a project ID
   */
  async scaffoldProject(projectId: string): Promise<{
    success: boolean;
    path: string;
    files_created: string[];
  }> {
    const projects = await this.vault.getProjects();
    const project = projects.find(p => p.id === projectId);
    if (!project) {
      throw new Error(`Project ${projectId} not found`);
    }

    const safeName = project.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
    const projectDir = path.join(PROJECTS_DIR, safeName);
    const filesCreated: string[] = [];

    // Create directory structure
    const dirs = [
      projectDir,
      path.join(projectDir, '.claude'),
      path.join(projectDir, '.beads'),
      path.join(projectDir, 'specs'),
      path.join(projectDir, 'src'),
      path.join(projectDir, 'src', 'components'),
      path.join(projectDir, 'src', 'services'),
      path.join(projectDir, 'src', 'routes'),
    ];

    for (const dir of dirs) {
      await fs.mkdir(dir, { recursive: true });
    }

    // Create CLAUDE.md
    const claudeMd = `# ${project.title}

## Project Description
${project.description || 'No description provided.'}

## Architecture
- Frontend: React + TypeScript + Tailwind CSS
- Backend: Express + TypeScript
- Data: File-based JSON vault at /srv/focus-flow/
- AI: OpenClaw gateway on port 18789

## Conventions
- Use TypeScript strict mode
- Functional React components with hooks
- Tailwind for styling (dark theme: bg-background-dark, text-white)
- Express 5 with async route handlers
- File-based storage via VaultService

## Key Files
- \`src/components/\` — React components
- \`src/services/\` — Backend services
- \`src/routes/\` — Express route handlers
- \`specs/\` — Technical specifications

## Testing
- Run tests: \`npm test\`
- Type check: \`npx tsc --noEmit\`
`;

    await fs.writeFile(path.join(projectDir, '.claude', 'CLAUDE.md'), claudeMd);
    filesCreated.push('.claude/CLAUDE.md');

    // Create initial bead
    const initialBead = JSON.stringify({
      version: 1,
      project_id: projectId,
      created_at: new Date().toISOString(),
      entries: [{
        timestamp: new Date().toISOString(),
        type: 'project_init',
        content: `Project "${project.title}" scaffolded by Focus Flow SpecKit`,
      }],
    }, null, 2);

    await fs.writeFile(path.join(projectDir, '.beads', 'init.json'), initialBead);
    filesCreated.push('.beads/init.json');

    // Create package.json
    const packageJson = JSON.stringify({
      name: safeName,
      version: '0.1.0',
      private: true,
      type: 'module',
      scripts: {
        dev: 'vite',
        build: 'tsc && vite build',
        preview: 'vite preview',
        test: 'vitest',
      },
    }, null, 2);

    await fs.writeFile(path.join(projectDir, 'package.json'), packageJson);
    filesCreated.push('package.json');

    // Create README
    const readme = `# ${project.title}\n\n${project.description || ''}\n\nGenerated by Focus Flow SpecKit.\n`;
    await fs.writeFile(path.join(projectDir, 'README.md'), readme);
    filesCreated.push('README.md');

    return {
      success: true,
      path: projectDir,
      files_created: filesCreated,
    };
  }

  /**
   * Generate specs for a project from its expanded idea
   */
  async generateSpecs(projectId: string): Promise<{
    success: boolean;
    spec_count: number;
    spec_path: string;
  }> {
    const projects = await this.vault.getProjects();
    const project = projects.find(p => p.id === projectId);
    if (!project) {
      throw new Error(`Project ${projectId} not found`);
    }

    const prd = {
      id: projectId,
      title: project.title,
      description: project.description || '',
      requirements: project.metadata?.requirements || ['Implement core functionality'],
      user_stories: project.metadata?.user_stories,
      constraints: project.metadata?.constraints,
      success_metrics: project.metadata?.success_metrics,
    };

    const specs = await this.specGenerator.generateFromPRD(prd as any);

    // Save specs to project directory
    const safeName = project.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '');
    const specDir = path.join(PROJECTS_DIR, safeName, 'specs');
    await fs.mkdir(specDir, { recursive: true });

    const specPath = path.join(specDir, `specs-${Date.now()}.json`);
    await fs.writeFile(specPath, JSON.stringify(specs, null, 2));

    return {
      success: true,
      spec_count: specs.length,
      spec_path: specPath,
    };
  }
}

export const specKitService = new SpecKitService();
